library(randomForest)
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0) {
  stop("Please specify the input file.", call.=FALSE)
} else {
  rf = readRDS("SRLModel.rds")
  data = read.csv(args[1],encoding="UTF-8",sep="\t")
  data$LEMMA_N = factor(data$LEMMA_N,levels=c("allos","anqrwpos","autos","eautou","egw","eu","gh","hmera","kalos","logos","mesos","nun","o","os","OTHER","outos","outws","pas","polis","polus","pws","qeos","su","tis","tis2","tropos","xronos"))
  data$LEMMA_V = factor(data$LEMMA_V,levels=c("agw","akouw","dew","didwmi","dokew","eimi","eiserxomai","erxomai","euxomai","exw","ferw","gignomai","grafw","isthmi","lambanw","legw","oraw","OTHER","parexw","pempw","poiew","poreuw","prassw","tiqhmi","xraw","zaw"))
  data$PREP = factor(data$PREP,levels=c("ama","ana","aneu","anti","apo","dia","eis","ek","en","enantion","eneka","epi","ews","kata","meta","mexri","none","OTHER","para","peri","pro","pros","sun","uper","upo","ws","xarin","xwris"))
  data$CASE = factor(data$CASE,levels=c("accusative","dative","genitive","none"))
  data$FORM_COMB = factor(data$FORM_COMB,levels=c("ama_dative","ana_accusative","aneu_genitive","anti_genitive","apo_genitive","bare_accusative","bare_dative","bare_genitive","dia_accusative","dia_genitive","eis_accusative","eis_none","ek_genitive","en_dative","enantion_genitive","eneka_genitive","epi_accusative","epi_dative","epi_genitive","ews_genitive","kata_accusative","kata_genitive","meta_accusative","meta_genitive","mexri_genitive","OTHER","para_accusative","para_dative","para_genitive","peri_accusative","peri_genitive","pro_genitive","pros_accusative","pros_dative","pros_genitive","sun_dative","uninflected","uper_genitive","upo_accusative","upo_dative","upo_genitive","ws_accusative","xarin_genitive","xwris_genitive"))
  data$SYNT = factor(data$SYNT,levels=c("OBJ","ADV","PNOM"))
  data$ANIMACY_N = factor(data$ANIMACY_N,levels=c("animal","concrete","group","nonconc","person","place","time","unknown"))
  data$POS_N = factor(data$POS_N,levels=c("adjective","adverb","article","demonstrative","indefinite","infinitive","interrogative","noun","numeral","participle","personal","relative","unknown"))
  data$GENDER_N = factor(data$GENDER_N,levels=c("common","feminine","masculine","neuter","none"))
  data$NUMBER_N = factor(data$NUMBER_N,levels=c("dual","none","plural","singular"))
  data$PERSON_V = factor(data$PERSON_V,levels=c("1st","2nd","3rd","none"))
  data$NUMBER_V = factor(data$NUMBER_V,levels=c("dual","none","plural","singular"))
  data$TENSE_V = factor(data$TENSE_V,levels=c("aorist","futperf","future","imperfect","none","perfect","pluperfect","present"))
  data$MOOD_V = factor(data$MOOD_V,levels=c("gerund","imperative","indicative","infinitive","none","optative","participle","subjunctive"))
  data$VOICE_V = factor(data$VOICE_V,levels=c("active","middle","none","passive"))
  prediction = predict(rf,data)
  write.table(prediction,file="pred_srl.txt",sep="\t",quote=FALSE,row.names=data$REF,col.names=FALSE)
}